WIP: pages
home-assistant/analytics.home-assistant.io pull request #37
Opened 2021-04-03 12:07 UTC by ludeeus

2021-04-03 22:34 UTC, bramkragten commented on site/src/analytics-element.ts
> +      this._currentPage = window.location.hash.replace("#", "");
I know it is WIP, but we should make sure the back button also works.

2021-04-03 22:36 UTC, bramkragten commented on site/src/analytics-element.ts
> +      this._currentPage = window.location.hash.replace("#", "");
You could then also drop the `page-changed` event

2021-04-05 17:45 UTC, bramkragten requested changes

2021-04-05 17:45 UTC, bramkragten commented on site/src/analytics-element.ts
> +    this._currentPage = this._currentPage =
Duplicate?

2021-04-05 17:45 UTC, bramkragten commented on site/src/analytics-header.ts
> +    this.currentPage = selectedPage;
This is already passed from the parent

2021-04-05 17:45 UTC, bramkragten commented on site/src/analytics-element.ts
> +    window.addEventListener("backbutton", () => this._pageChanged(), false);
What is this event?

2021-04-06 08:49 UTC, ludeeus commented on site/src/analytics-element.ts
> +    window.addEventListener("backbutton", () => this._pageChanged(), false);
wishful thinking

2021-04-07 10:31 UTC, bramkragten approved these changes

2021-04-07 10:37 UTC, merged