Show average rounded to 2 decimal on hover
home-assistant/analytics.home-assistant.io pull request #61
Opened 2021-04-08 12:05 UTC by LiJu09

I don't know if it's useful, but it can be especially for users because it's a small amount, and maybe 1 decimal would be enough.
I know it's doesn't work on touchscreens, but if this will be approved I can add it.
Or are there any plans for adding more features such as graphs, where it would be rounded to at least 1 decimal place?

2021-04-08 13:01 UTC, Adminiuga commented
Some people may want 0.01 steps

2021-04-09 20:33 UTC, ludeeus requested changes
Let's create const above the return statement and reference those

```js

const integrations = this.lastDataEntry.avg_integrations.toFixed(2);
...

return html...
...
<div class="metric">
  <span>Average integrations</span>
  <span .title=${integrations}>
    ${Math.round(Number(integrations))}
  </span>
</div>
```

2021-04-09 20:33 UTC, ludeeus commented on site/src/analytics-average.ts
> +            title="${Math.round(this.lastDataEntry.avg_integrations * 100) /
Use  `.title=${}` instead of `title="${}"`

2021-04-09 21:22 UTC, ludeeus approved these changes
As for your questions about the future, there are currently no plans and the history part of the dataset does not currently include this, so there is nothing to graph really.

2021-04-09 21:23 UTC, merged

2021-04-09 21:28 UTC, LiJu09 commented
And something like this for touchscreen it's necessary?

2021-04-09 21:42 UTC, ludeeus commented
No graphs are not needed for touch

2021-04-09 21:53 UTC, LiJu09 commented
I mean that pop up on hover.

2021-04-09 22:07 UTC, ludeeus commented
<https://material.io/components/tooltips#behavior> Have a look here.